// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9h15WZQtZw7OlSW3ZarXil3n7K5znoQY',
    appId: '1:469497701352:web:825e261c80ef7376c43a5d',
    messagingSenderId: '469497701352',
    projectId: 'dotog-26f44',
    authDomain: 'dotog-26f44.firebaseapp.com',
    storageBucket: 'dotog-26f44.firebasestorage.app',
    measurementId: 'G-4RSSDG4B4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLJbH1fYtefyNn0lTvVuRpatvG30lr8AQ',
    appId: '1:469497701352:android:f23ac571949aac86c43a5d',
    messagingSenderId: '469497701352',
    projectId: 'dotog-26f44',
    storageBucket: 'dotog-26f44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkt0WNinWmG1IGz2hx3sQWUvh1GaB7n30',
    appId: '1:469497701352:ios:4a0bfa666ac0ffeec43a5d',
    messagingSenderId: '469497701352',
    projectId: 'dotog-26f44',
    storageBucket: 'dotog-26f44.firebasestorage.app',
    iosClientId: '469497701352-kt5aqrqgi8agqvi3anuerpcu761mgk1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.dotog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkt0WNinWmG1IGz2hx3sQWUvh1GaB7n30',
    appId: '1:469497701352:ios:4a0bfa666ac0ffeec43a5d',
    messagingSenderId: '469497701352',
    projectId: 'dotog-26f44',
    storageBucket: 'dotog-26f44.firebasestorage.app',
    iosClientId: '469497701352-kt5aqrqgi8agqvi3anuerpcu761mgk1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.dotog',
  );

}